Customizable installation
AdaCore/gnat_community_install_script pull request #7
Opened 2019-09-15 12:01 UTC by damaki

These changes allow the user to customize the installation by specifying the exact set of components that they want to install. This is useful to, for example, install only the SPARK 2014 toolset without installing GNAT and everything else.

The set of components to install is specified as an optional third argument to the `install_package` scripts, which specifies the components as a comma-separated list (no spaces). E.g. `com.adacore.gnat` specifies the GNAT component. 

These changes are backwards compatible with the existing behaviour. If this new argument is omitted, then all components are installed.

Here's an example of using this script to install only the SPARK 2014 Discovery component from GNAT Community 2019 to `~/opt/GNAT/2019`:

```
install_script.sh gnat-community-2019-20190517-x86_64-linux-bin ~/opt/GNAT/2019 com.adacore.spark2014_discovery
```

2019-09-15 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdaCore/gnat_community_install_script?pullRequest=7) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdaCore/gnat_community_install_script?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdaCore/gnat_community_install_script?pullRequest=7) it.</sub>

2019-09-15 12:08 UTC, damaki commented
Please note that I have only been able to test this on Linux with `install_package.sh`. I don't have a Windows or Mac machine available to test my changes on these other platforms.

2019-10-30 14:39 UTC, setton commented
Thank you @damaki ! we will have a look ASAP, sorry for the delay!

2019-11-11 17:48 UTC, setton requested changes

2019-11-11 17:48 UTC, setton commented on install_package.bat
> +%package% --script install_script.qs InstallPrefix="%target% Components="%components%"
missing a `"` after `%target%`

2019-11-13 20:50 UTC, damaki commented on install_package.bat
> +%package% --script install_script.qs InstallPrefix="%target% Components="%components%"
Fixed in 97a995b.

2019-11-13 21:10 UTC, setton commented on install_package.bat
> +%package% --script install_script.qs InstallPrefix="%target% Components="%components%"
Excellent, thank you!

2019-11-13 21:10 UTC, setton approved these changes

2019-11-13 21:11 UTC, merged

2019-11-13 21:12 UTC, setton commented
Thank you @damaki for the PR!